package uk.ac.bristol.enums;

public enum Location {

    BRISTOL_CITY_FOOTBALL_CLUB_ASHTON_GATE,
    COOMBE_DINGLE_SPORTS_CENTRE,
    EXTERNAL,
    LAW_DEPARTMENT,
    LANGFORD,
    LONG_ASHTON,
    MAIN_PRECINCT,
    PASSENGER_SHED_TEMPLE_MEADS_FORMER_COMMONWEALTH,
    PITHAY_CITY_CENTRE,
    UNIVERSTIY_OF_BRISTOL,
    UNIVERSITY_OF_THE_WEST_OF_ENGLAND;

    Location() {

    }
}
